### ISSUE TITLE
关于使用该框架来让Android设备作为Server接收文件的问题？

### ISSUE THREAD

**Issue by soyoungboy** [570622566/FNetServer#1]
```java
public class WeChatController {
    public static final String OK = "上传成功";
    @ResponseBody
    @RequestMapping("upload")
    public NanoHTTPD.Response upload(NanoHTTPD.IHTTPSession session) {
        FFileUploadUtils.uploadFile(session, FFileUtils.getRootDir(), "file");
        return NanoHTTPDUtil.setResponse(NanoHTTPD.Response.Status.OK, OK);
    }
}

Application里面：

    /**
     * 启动HttpServer
     */
    private fun initFHttpManager() {
        fHttpManager = FHttpManager.init(this, WeChatController::class.java)
                .setPort(9999)
                .setAllowCross(true)
                .startServer()
    }
```
如上代码来让Android设备作为Server接收文件，但是我用postman测试上传无法ok，不知道有什么特殊的写法或者配置？
![image](https://user-images.githubusercontent.com/8855422/102055988-a00fc700-3e26-11eb-88cd-ccd3dcb9c67e.png)

**Comment by 570622566** [comment]
1. 手机关闭wifi 重新打开
2. 
![image](https://user-images.githubusercontent.com/6415417/102063027-78256100-3e30-11eb-86ab-e9c81b07f9c6.png)
那参数就是 postman 的key

**Comment by 570622566** [comment]
手机关闭wifi 重新打开试试




那参数就是 postman 的key&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "570622566/FNetServer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午4:09
收件人:&nbsp;"570622566/FNetServer"<FNetServer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[570622566/FNetServer] 关于使用该框架来让Android设备作为Server接收文件的问题？ (#1)





 public class WeChatController {     public static final String OK = "上传成功";     @ResponseBody     @RequestMapping("upload")     public NanoHTTPD.Response upload(NanoHTTPD.IHTTPSession session) {         FFileUploadUtils.uploadFile(session, FFileUtils.getRootDir(), "file");         return NanoHTTPDUtil.setResponse(NanoHTTPD.Response.Status.OK, OK);     } } Application里面：     /**      * 启动HttpServer      */     private fun initFHttpManager() {         fHttpManager = FHttpManager.init(this, WeChatController::class.java)                 .setPort(9999)                 .setAllowCross(true)                 .startServer()     }
 
如上代码来让Android设备作为Server接收文件，但是我用postman测试上传无法ok，不知道有什么特殊的写法或者配置？
